# 服务端口
server:
  port: 8081


spring:
    application:
      name: springcloud-provider-user
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.101.93:3306/jwnming?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: mysql123

mybatis:
  type-aliases-package: com.jwnming.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


eureka:
  client:
    service-url:
      defaultZone: http://jwnming.eureka8000.com:8000/eureka/,http://jwnming.eureka8001.com:8001/eureka/,http://jwnming.eureka8002.com:8002/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: springcloud-provider-user # 修改eureka页面描述信息
    prefer-ip-address: false # eureka监控页面，悬浮微服务连接不展示ip信息


# info:可以配置eureka监控信息，微服务对应首页或简介等
info:
  app.name: jwnming-springcloud
  company.name: jwnming.com
  desc: 微服务user提供者